/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FilesRouteImport } from './routes/files'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as OrganizationRecommendationsRouteImport } from './routes/organization-recommendations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StorageConnectionsRouteImport } from './routes/storage-connections'
import { Route as StorageIntelligenceRouteImport } from './routes/storage-intelligence'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ArchivesIndexRouteImport } from './routes/archives.index'
import { Route as ArchivesArchiveIdRouteImport } from './routes/archives.$archiveId'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatConversationIdRouteImport } from './routes/chat.$conversationId'
import { Route as FilesIndexRouteImport } from './routes/files.index'
import { Route as FilesFileIdRouteImport } from './routes/files.$fileId'
import { Route as OrganizationRecommendationsIndexRouteImport } from './routes/organization-recommendations.index'
import { Route as OrganizationRecommendationsRecommendationIdRouteImport } from './routes/organization-recommendations.$recommendationId'
import { Route as RecommendationsIndexRouteImport } from './routes/recommendations.index'
import { Route as RecommendationsRecommendationIdRouteImport } from './routes/recommendations.$recommendationId'
import { Route as StorageIntelligenceIndexRouteImport } from './routes/storage-intelligence.index'
import { Route as StorageIntelligenceCandidatesRouteImport } from './routes/storage-intelligence.candidates'
import { Route as StorageIntelligenceDuplicatesRouteImport } from './routes/storage-intelligence.duplicates'
import { Route as StorageIntelligenceInactiveFilesRouteImport } from './routes/storage-intelligence.inactive-files'
import { Route as StorageIntelligenceLargeFilesRouteImport } from './routes/storage-intelligence.large-files'
import { Route as StorageIntelligenceOldFilesRouteImport } from './routes/storage-intelligence.old-files'
import { Route as TrashIndexRouteImport } from './routes/trash.index'
import { Route as ConnectorsGoogleCallbackRouteImport } from './routes/connectors.google.callback'
import { Route as StorageIntelligenceDuplicatesIndexRouteImport } from './routes/storage-intelligence.duplicates.index'
import { Route as StorageIntelligenceDuplicatesGroupIdRouteImport } from './routes/storage-intelligence.duplicates.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRecommendationsRoute =
  OrganizationRecommendationsRouteImport.update({
    id: '/organization-recommendations',
    path: '/organization-recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageConnectionsRoute = StorageConnectionsRouteImport.update({
  id: '/storage-connections',
  path: '/storage-connections',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageIntelligenceRoute = StorageIntelligenceRouteImport.update({
  id: '/storage-intelligence',
  path: '/storage-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesIndexRoute = ArchivesIndexRouteImport.update({
  id: '/archives/',
  path: '/archives/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesArchiveIdRoute = ArchivesArchiveIdRouteImport.update({
  id: '/archives/$archiveId',
  path: '/archives/$archiveId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => ChatRoute,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilesRoute,
} as any)
const FilesFileIdRoute = FilesFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => FilesRoute,
} as any)
const OrganizationRecommendationsIndexRoute =
  OrganizationRecommendationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationRecommendationsRoute,
  } as any)
const OrganizationRecommendationsRecommendationIdRoute =
  OrganizationRecommendationsRecommendationIdRouteImport.update({
    id: '/$recommendationId',
    path: '/$recommendationId',
    getParentRoute: () => OrganizationRecommendationsRoute,
  } as any)
const RecommendationsIndexRoute = RecommendationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecommendationsRoute,
} as any)
const RecommendationsRecommendationIdRoute =
  RecommendationsRecommendationIdRouteImport.update({
    id: '/$recommendationId',
    path: '/$recommendationId',
    getParentRoute: () => RecommendationsRoute,
  } as any)
const StorageIntelligenceIndexRoute =
  StorageIntelligenceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StorageIntelligenceRoute,
  } as any)
const StorageIntelligenceCandidatesRoute =
  StorageIntelligenceCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => StorageIntelligenceRoute,
  } as any)
const StorageIntelligenceDuplicatesRoute =
  StorageIntelligenceDuplicatesRouteImport.update({
    id: '/duplicates',
    path: '/duplicates',
    getParentRoute: () => StorageIntelligenceRoute,
  } as any)
const StorageIntelligenceInactiveFilesRoute =
  StorageIntelligenceInactiveFilesRouteImport.update({
    id: '/inactive-files',
    path: '/inactive-files',
    getParentRoute: () => StorageIntelligenceRoute,
  } as any)
const StorageIntelligenceLargeFilesRoute =
  StorageIntelligenceLargeFilesRouteImport.update({
    id: '/large-files',
    path: '/large-files',
    getParentRoute: () => StorageIntelligenceRoute,
  } as any)
const StorageIntelligenceOldFilesRoute =
  StorageIntelligenceOldFilesRouteImport.update({
    id: '/old-files',
    path: '/old-files',
    getParentRoute: () => StorageIntelligenceRoute,
  } as any)
const TrashIndexRoute = TrashIndexRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsGoogleCallbackRoute =
  ConnectorsGoogleCallbackRouteImport.update({
    id: '/connectors/google/callback',
    path: '/connectors/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const StorageIntelligenceDuplicatesIndexRoute =
  StorageIntelligenceDuplicatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StorageIntelligenceDuplicatesRoute,
  } as any)
const StorageIntelligenceDuplicatesGroupIdRoute =
  StorageIntelligenceDuplicatesGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => StorageIntelligenceDuplicatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRouteWithChildren
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRoute
  '/organization-recommendations': typeof OrganizationRecommendationsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRouteWithChildren
  '/scans': typeof ScansRoute
  '/search': typeof SearchRoute
  '/storage-connections': typeof StorageConnectionsRoute
  '/storage-intelligence': typeof StorageIntelligenceRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/archives/$archiveId': typeof ArchivesArchiveIdRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/organization-recommendations/$recommendationId': typeof OrganizationRecommendationsRecommendationIdRoute
  '/recommendations/$recommendationId': typeof RecommendationsRecommendationIdRoute
  '/storage-intelligence/candidates': typeof StorageIntelligenceCandidatesRoute
  '/storage-intelligence/duplicates': typeof StorageIntelligenceDuplicatesRouteWithChildren
  '/storage-intelligence/inactive-files': typeof StorageIntelligenceInactiveFilesRoute
  '/storage-intelligence/large-files': typeof StorageIntelligenceLargeFilesRoute
  '/storage-intelligence/old-files': typeof StorageIntelligenceOldFilesRoute
  '/archives/': typeof ArchivesIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/files/': typeof FilesIndexRoute
  '/organization-recommendations/': typeof OrganizationRecommendationsIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/storage-intelligence/': typeof StorageIntelligenceIndexRoute
  '/trash/': typeof TrashIndexRoute
  '/connectors/google/callback': typeof ConnectorsGoogleCallbackRoute
  '/storage-intelligence/duplicates/$groupId': typeof StorageIntelligenceDuplicatesGroupIdRoute
  '/storage-intelligence/duplicates/': typeof StorageIntelligenceDuplicatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRoute
  '/profile': typeof ProfileRoute
  '/scans': typeof ScansRoute
  '/search': typeof SearchRoute
  '/storage-connections': typeof StorageConnectionsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/archives/$archiveId': typeof ArchivesArchiveIdRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/organization-recommendations/$recommendationId': typeof OrganizationRecommendationsRecommendationIdRoute
  '/recommendations/$recommendationId': typeof RecommendationsRecommendationIdRoute
  '/storage-intelligence/candidates': typeof StorageIntelligenceCandidatesRoute
  '/storage-intelligence/inactive-files': typeof StorageIntelligenceInactiveFilesRoute
  '/storage-intelligence/large-files': typeof StorageIntelligenceLargeFilesRoute
  '/storage-intelligence/old-files': typeof StorageIntelligenceOldFilesRoute
  '/archives': typeof ArchivesIndexRoute
  '/chat': typeof ChatIndexRoute
  '/files': typeof FilesIndexRoute
  '/organization-recommendations': typeof OrganizationRecommendationsIndexRoute
  '/recommendations': typeof RecommendationsIndexRoute
  '/storage-intelligence': typeof StorageIntelligenceIndexRoute
  '/trash': typeof TrashIndexRoute
  '/connectors/google/callback': typeof ConnectorsGoogleCallbackRoute
  '/storage-intelligence/duplicates/$groupId': typeof StorageIntelligenceDuplicatesGroupIdRoute
  '/storage-intelligence/duplicates': typeof StorageIntelligenceDuplicatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/files': typeof FilesRouteWithChildren
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRoute
  '/organization-recommendations': typeof OrganizationRecommendationsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRouteWithChildren
  '/scans': typeof ScansRoute
  '/search': typeof SearchRoute
  '/storage-connections': typeof StorageConnectionsRoute
  '/storage-intelligence': typeof StorageIntelligenceRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/archives/$archiveId': typeof ArchivesArchiveIdRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/organization-recommendations/$recommendationId': typeof OrganizationRecommendationsRecommendationIdRoute
  '/recommendations/$recommendationId': typeof RecommendationsRecommendationIdRoute
  '/storage-intelligence/candidates': typeof StorageIntelligenceCandidatesRoute
  '/storage-intelligence/duplicates': typeof StorageIntelligenceDuplicatesRouteWithChildren
  '/storage-intelligence/inactive-files': typeof StorageIntelligenceInactiveFilesRoute
  '/storage-intelligence/large-files': typeof StorageIntelligenceLargeFilesRoute
  '/storage-intelligence/old-files': typeof StorageIntelligenceOldFilesRoute
  '/archives/': typeof ArchivesIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/files/': typeof FilesIndexRoute
  '/organization-recommendations/': typeof OrganizationRecommendationsIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/storage-intelligence/': typeof StorageIntelligenceIndexRoute
  '/trash/': typeof TrashIndexRoute
  '/connectors/google/callback': typeof ConnectorsGoogleCallbackRoute
  '/storage-intelligence/duplicates/$groupId': typeof StorageIntelligenceDuplicatesGroupIdRoute
  '/storage-intelligence/duplicates/': typeof StorageIntelligenceDuplicatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/files'
    | '/login'
    | '/organization'
    | '/organization-recommendations'
    | '/profile'
    | '/recommendations'
    | '/scans'
    | '/search'
    | '/storage-connections'
    | '/storage-intelligence'
    | '/unauthorized'
    | '/archives/$archiveId'
    | '/chat/$conversationId'
    | '/files/$fileId'
    | '/organization-recommendations/$recommendationId'
    | '/recommendations/$recommendationId'
    | '/storage-intelligence/candidates'
    | '/storage-intelligence/duplicates'
    | '/storage-intelligence/inactive-files'
    | '/storage-intelligence/large-files'
    | '/storage-intelligence/old-files'
    | '/archives/'
    | '/chat/'
    | '/files/'
    | '/organization-recommendations/'
    | '/recommendations/'
    | '/storage-intelligence/'
    | '/trash/'
    | '/connectors/google/callback'
    | '/storage-intelligence/duplicates/$groupId'
    | '/storage-intelligence/duplicates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/organization'
    | '/profile'
    | '/scans'
    | '/search'
    | '/storage-connections'
    | '/unauthorized'
    | '/archives/$archiveId'
    | '/chat/$conversationId'
    | '/files/$fileId'
    | '/organization-recommendations/$recommendationId'
    | '/recommendations/$recommendationId'
    | '/storage-intelligence/candidates'
    | '/storage-intelligence/inactive-files'
    | '/storage-intelligence/large-files'
    | '/storage-intelligence/old-files'
    | '/archives'
    | '/chat'
    | '/files'
    | '/organization-recommendations'
    | '/recommendations'
    | '/storage-intelligence'
    | '/trash'
    | '/connectors/google/callback'
    | '/storage-intelligence/duplicates/$groupId'
    | '/storage-intelligence/duplicates'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/files'
    | '/login'
    | '/organization'
    | '/organization-recommendations'
    | '/profile'
    | '/recommendations'
    | '/scans'
    | '/search'
    | '/storage-connections'
    | '/storage-intelligence'
    | '/unauthorized'
    | '/archives/$archiveId'
    | '/chat/$conversationId'
    | '/files/$fileId'
    | '/organization-recommendations/$recommendationId'
    | '/recommendations/$recommendationId'
    | '/storage-intelligence/candidates'
    | '/storage-intelligence/duplicates'
    | '/storage-intelligence/inactive-files'
    | '/storage-intelligence/large-files'
    | '/storage-intelligence/old-files'
    | '/archives/'
    | '/chat/'
    | '/files/'
    | '/organization-recommendations/'
    | '/recommendations/'
    | '/storage-intelligence/'
    | '/trash/'
    | '/connectors/google/callback'
    | '/storage-intelligence/duplicates/$groupId'
    | '/storage-intelligence/duplicates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FilesRoute: typeof FilesRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrganizationRoute: typeof OrganizationRoute
  OrganizationRecommendationsRoute: typeof OrganizationRecommendationsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRouteWithChildren
  ScansRoute: typeof ScansRoute
  SearchRoute: typeof SearchRoute
  StorageConnectionsRoute: typeof StorageConnectionsRoute
  StorageIntelligenceRoute: typeof StorageIntelligenceRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  ArchivesArchiveIdRoute: typeof ArchivesArchiveIdRoute
  ArchivesIndexRoute: typeof ArchivesIndexRoute
  TrashIndexRoute: typeof TrashIndexRoute
  ConnectorsGoogleCallbackRoute: typeof ConnectorsGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization-recommendations': {
      id: '/organization-recommendations'
      path: '/organization-recommendations'
      fullPath: '/organization-recommendations'
      preLoaderRoute: typeof OrganizationRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage-connections': {
      id: '/storage-connections'
      path: '/storage-connections'
      fullPath: '/storage-connections'
      preLoaderRoute: typeof StorageConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage-intelligence': {
      id: '/storage-intelligence'
      path: '/storage-intelligence'
      fullPath: '/storage-intelligence'
      preLoaderRoute: typeof StorageIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives/': {
      id: '/archives/'
      path: '/archives'
      fullPath: '/archives/'
      preLoaderRoute: typeof ArchivesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives/$archiveId': {
      id: '/archives/$archiveId'
      path: '/archives/$archiveId'
      fullPath: '/archives/$archiveId'
      preLoaderRoute: typeof ArchivesArchiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/files/': {
      id: '/files/'
      path: '/'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof FilesRoute
    }
    '/files/$fileId': {
      id: '/files/$fileId'
      path: '/$fileId'
      fullPath: '/files/$fileId'
      preLoaderRoute: typeof FilesFileIdRouteImport
      parentRoute: typeof FilesRoute
    }
    '/organization-recommendations/': {
      id: '/organization-recommendations/'
      path: '/'
      fullPath: '/organization-recommendations/'
      preLoaderRoute: typeof OrganizationRecommendationsIndexRouteImport
      parentRoute: typeof OrganizationRecommendationsRoute
    }
    '/organization-recommendations/$recommendationId': {
      id: '/organization-recommendations/$recommendationId'
      path: '/$recommendationId'
      fullPath: '/organization-recommendations/$recommendationId'
      preLoaderRoute: typeof OrganizationRecommendationsRecommendationIdRouteImport
      parentRoute: typeof OrganizationRecommendationsRoute
    }
    '/recommendations/': {
      id: '/recommendations/'
      path: '/'
      fullPath: '/recommendations/'
      preLoaderRoute: typeof RecommendationsIndexRouteImport
      parentRoute: typeof RecommendationsRoute
    }
    '/recommendations/$recommendationId': {
      id: '/recommendations/$recommendationId'
      path: '/$recommendationId'
      fullPath: '/recommendations/$recommendationId'
      preLoaderRoute: typeof RecommendationsRecommendationIdRouteImport
      parentRoute: typeof RecommendationsRoute
    }
    '/storage-intelligence/': {
      id: '/storage-intelligence/'
      path: '/'
      fullPath: '/storage-intelligence/'
      preLoaderRoute: typeof StorageIntelligenceIndexRouteImport
      parentRoute: typeof StorageIntelligenceRoute
    }
    '/storage-intelligence/candidates': {
      id: '/storage-intelligence/candidates'
      path: '/candidates'
      fullPath: '/storage-intelligence/candidates'
      preLoaderRoute: typeof StorageIntelligenceCandidatesRouteImport
      parentRoute: typeof StorageIntelligenceRoute
    }
    '/storage-intelligence/duplicates': {
      id: '/storage-intelligence/duplicates'
      path: '/duplicates'
      fullPath: '/storage-intelligence/duplicates'
      preLoaderRoute: typeof StorageIntelligenceDuplicatesRouteImport
      parentRoute: typeof StorageIntelligenceRoute
    }
    '/storage-intelligence/inactive-files': {
      id: '/storage-intelligence/inactive-files'
      path: '/inactive-files'
      fullPath: '/storage-intelligence/inactive-files'
      preLoaderRoute: typeof StorageIntelligenceInactiveFilesRouteImport
      parentRoute: typeof StorageIntelligenceRoute
    }
    '/storage-intelligence/large-files': {
      id: '/storage-intelligence/large-files'
      path: '/large-files'
      fullPath: '/storage-intelligence/large-files'
      preLoaderRoute: typeof StorageIntelligenceLargeFilesRouteImport
      parentRoute: typeof StorageIntelligenceRoute
    }
    '/storage-intelligence/old-files': {
      id: '/storage-intelligence/old-files'
      path: '/old-files'
      fullPath: '/storage-intelligence/old-files'
      preLoaderRoute: typeof StorageIntelligenceOldFilesRouteImport
      parentRoute: typeof StorageIntelligenceRoute
    }
    '/trash/': {
      id: '/trash/'
      path: '/trash'
      fullPath: '/trash/'
      preLoaderRoute: typeof TrashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/google/callback': {
      id: '/connectors/google/callback'
      path: '/connectors/google/callback'
      fullPath: '/connectors/google/callback'
      preLoaderRoute: typeof ConnectorsGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage-intelligence/duplicates/': {
      id: '/storage-intelligence/duplicates/'
      path: '/'
      fullPath: '/storage-intelligence/duplicates/'
      preLoaderRoute: typeof StorageIntelligenceDuplicatesIndexRouteImport
      parentRoute: typeof StorageIntelligenceDuplicatesRoute
    }
    '/storage-intelligence/duplicates/$groupId': {
      id: '/storage-intelligence/duplicates/$groupId'
      path: '/$groupId'
      fullPath: '/storage-intelligence/duplicates/$groupId'
      preLoaderRoute: typeof StorageIntelligenceDuplicatesGroupIdRouteImport
      parentRoute: typeof StorageIntelligenceDuplicatesRoute
    }
  }
}

interface ChatRouteChildren {
  ChatConversationIdRoute: typeof ChatConversationIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatConversationIdRoute: ChatConversationIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface FilesRouteChildren {
  FilesFileIdRoute: typeof FilesFileIdRoute
  FilesIndexRoute: typeof FilesIndexRoute
}

const FilesRouteChildren: FilesRouteChildren = {
  FilesFileIdRoute: FilesFileIdRoute,
  FilesIndexRoute: FilesIndexRoute,
}

const FilesRouteWithChildren = FilesRoute._addFileChildren(FilesRouteChildren)

interface OrganizationRecommendationsRouteChildren {
  OrganizationRecommendationsRecommendationIdRoute: typeof OrganizationRecommendationsRecommendationIdRoute
  OrganizationRecommendationsIndexRoute: typeof OrganizationRecommendationsIndexRoute
}

const OrganizationRecommendationsRouteChildren: OrganizationRecommendationsRouteChildren =
  {
    OrganizationRecommendationsRecommendationIdRoute:
      OrganizationRecommendationsRecommendationIdRoute,
    OrganizationRecommendationsIndexRoute:
      OrganizationRecommendationsIndexRoute,
  }

const OrganizationRecommendationsRouteWithChildren =
  OrganizationRecommendationsRoute._addFileChildren(
    OrganizationRecommendationsRouteChildren,
  )

interface RecommendationsRouteChildren {
  RecommendationsRecommendationIdRoute: typeof RecommendationsRecommendationIdRoute
  RecommendationsIndexRoute: typeof RecommendationsIndexRoute
}

const RecommendationsRouteChildren: RecommendationsRouteChildren = {
  RecommendationsRecommendationIdRoute: RecommendationsRecommendationIdRoute,
  RecommendationsIndexRoute: RecommendationsIndexRoute,
}

const RecommendationsRouteWithChildren = RecommendationsRoute._addFileChildren(
  RecommendationsRouteChildren,
)

interface StorageIntelligenceDuplicatesRouteChildren {
  StorageIntelligenceDuplicatesGroupIdRoute: typeof StorageIntelligenceDuplicatesGroupIdRoute
  StorageIntelligenceDuplicatesIndexRoute: typeof StorageIntelligenceDuplicatesIndexRoute
}

const StorageIntelligenceDuplicatesRouteChildren: StorageIntelligenceDuplicatesRouteChildren =
  {
    StorageIntelligenceDuplicatesGroupIdRoute:
      StorageIntelligenceDuplicatesGroupIdRoute,
    StorageIntelligenceDuplicatesIndexRoute:
      StorageIntelligenceDuplicatesIndexRoute,
  }

const StorageIntelligenceDuplicatesRouteWithChildren =
  StorageIntelligenceDuplicatesRoute._addFileChildren(
    StorageIntelligenceDuplicatesRouteChildren,
  )

interface StorageIntelligenceRouteChildren {
  StorageIntelligenceCandidatesRoute: typeof StorageIntelligenceCandidatesRoute
  StorageIntelligenceDuplicatesRoute: typeof StorageIntelligenceDuplicatesRouteWithChildren
  StorageIntelligenceInactiveFilesRoute: typeof StorageIntelligenceInactiveFilesRoute
  StorageIntelligenceLargeFilesRoute: typeof StorageIntelligenceLargeFilesRoute
  StorageIntelligenceOldFilesRoute: typeof StorageIntelligenceOldFilesRoute
  StorageIntelligenceIndexRoute: typeof StorageIntelligenceIndexRoute
}

const StorageIntelligenceRouteChildren: StorageIntelligenceRouteChildren = {
  StorageIntelligenceCandidatesRoute: StorageIntelligenceCandidatesRoute,
  StorageIntelligenceDuplicatesRoute:
    StorageIntelligenceDuplicatesRouteWithChildren,
  StorageIntelligenceInactiveFilesRoute: StorageIntelligenceInactiveFilesRoute,
  StorageIntelligenceLargeFilesRoute: StorageIntelligenceLargeFilesRoute,
  StorageIntelligenceOldFilesRoute: StorageIntelligenceOldFilesRoute,
  StorageIntelligenceIndexRoute: StorageIntelligenceIndexRoute,
}

const StorageIntelligenceRouteWithChildren =
  StorageIntelligenceRoute._addFileChildren(StorageIntelligenceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FilesRoute: FilesRouteWithChildren,
  LoginRoute: LoginRoute,
  OrganizationRoute: OrganizationRoute,
  OrganizationRecommendationsRoute:
    OrganizationRecommendationsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRouteWithChildren,
  ScansRoute: ScansRoute,
  SearchRoute: SearchRoute,
  StorageConnectionsRoute: StorageConnectionsRoute,
  StorageIntelligenceRoute: StorageIntelligenceRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  ArchivesArchiveIdRoute: ArchivesArchiveIdRoute,
  ArchivesIndexRoute: ArchivesIndexRoute,
  TrashIndexRoute: TrashIndexRoute,
  ConnectorsGoogleCallbackRoute: ConnectorsGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
